// Static seed data — used when Supabase is unavailable.
// Mirrors the data the client provided directly.

import type {
  Branch,
  Service,
  Barber,
  Review,
  BusinessSettings,
  SocialLink,
  GalleryItem,
} from "@/types/database";

export const SEED_SETTINGS: BusinessSettings = {
  shop_id: "default",
  business_name: "Kemekem Barbershop",
  tagline: "Look Sharp. Book in Seconds.",
  logo_url: null,
  favicon_url: null,
  hero_image_url:
    "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1920&q=80",
  hero_video_url: null,
  phone: "+251 924 657 777",
  email: "kemekemedia01@gmail.com",
  address: "Addis Ababa, Ethiopia",
  maps_url: null,
  business_hours: { open: "08:00", close: "20:00", days: "Mon-Sun" },
  primary_color: "#000000",
  booking_interval_minutes: 60,
  seo_title: "Kemekem Barbershop — Premium Grooming in Addis Ababa",
  seo_description:
    "Professional grooming experience with skilled barbers in Addis Ababa. Book your appointment online in seconds.",
  seo_keywords:
    "barbershop, addis ababa, haircut, beard, premium grooming, kemekem",
  og_image_url: null,
  footer_text: "Designed with care for modern grooming.",
  updated_at: new Date().toISOString(),
};

export const SEED_BRANCHES: Branch[] = [
  {
    id: "piassa",
    shop_id: null,
    name: "Piassa Branch",
    address: "Piassa Shopping Mall, 6th Floor, Addis Ababa, Ethiopia",
    city: "Addis Ababa",
    phone: "+251 924 657 777",
    maps_url: "https://maps.google.com/?q=Piassa+Shopping+Mall+Addis+Ababa",
    working_hours: { open: "08:00", close: "20:00" },
    is_active: true,
    display_order: 1,
    created_at: "",
    updated_at: "",
  },
  {
    id: "bole",
    shop_id: null,
    name: "Bole Branch",
    address: "Sapphire Addis Hotel, 11th Floor, Bole, Addis Ababa, Ethiopia",
    city: "Addis Ababa",
    phone: "+251 924 657 777",
    maps_url: "https://maps.google.com/?q=Sapphire+Addis+Hotel+Bole",
    working_hours: { open: "08:00", close: "20:00" },
    is_active: true,
    display_order: 2,
    created_at: "",
    updated_at: "",
  },
];

export const SEED_SERVICES: Service[] = [
  {
    id: "haircut",
    shop_id: null,
    name: "Haircut",
    description: "Precision cut tailored to your face shape and style.",
    image_url:
      "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 60,
    price: 500,
    category: "haircut",
    is_visible: true,
    display_order: 1,
    created_at: "",
    updated_at: "",
  },
  {
    id: "shampoo",
    shop_id: null,
    name: "Shampoo / Hair Wash",
    description: "Refreshing wash, scalp massage, and towel dry.",
    image_url:
      "https://images.unsplash.com/photo-1559599076-9c61d8e1b77c?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 30,
    price: 300,
    category: "haircare",
    is_visible: true,
    display_order: 2,
    created_at: "",
    updated_at: "",
  },
  {
    id: "finger-coils",
    shop_id: null,
    name: "Finger Coils",
    description: "Hand-shaped coils for a bold, defined look.",
    image_url:
      "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 90,
    price: 800,
    category: "haircare",
    is_visible: true,
    display_order: 3,
    created_at: "",
    updated_at: "",
  },
  {
    id: "braids-haircut",
    shop_id: null,
    name: "Braids/Twists + Haircut",
    description: "Stylish braids or twists combined with a precision cut.",
    image_url:
      "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 120,
    price: 3000,
    category: "special",
    is_visible: true,
    display_order: 4,
    created_at: "",
    updated_at: "",
  },
  {
    id: "braids-extensions",
    shop_id: null,
    name: "Braids/Twists with Extensions + Haircut",
    description: "Premium braided styles with extensions and a precision cut.",
    image_url:
      "https://images.unsplash.com/photo-1605497777774-9b2f55bda7be?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 180,
    price: 4000,
    category: "special",
    is_visible: true,
    display_order: 5,
    created_at: "",
    updated_at: "",
  },
  {
    id: "full-package-basic",
    shop_id: null,
    name: "Haircut + Shampoo + Face Mask + Hair Gel + Black Color",
    description: "Complete grooming package: cut, wash, face mask, gel and black color.",
    image_url:
      "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 90,
    price: 1300,
    category: "package",
    is_visible: true,
    display_order: 6,
    created_at: "",
    updated_at: "",
  },
  {
    id: "special-color",
    shop_id: null,
    name: "Special Hair Color",
    description: "Premium special coloring service for a striking look.",
    image_url:
      "https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 90,
    price: 4000,
    category: "color",
    is_visible: true,
    display_order: 7,
    created_at: "",
    updated_at: "",
  },
  {
    id: "color-package",
    shop_id: null,
    name: "Haircut + Black Color + Shampoo",
    description: "Cut, black color and shampoo — clean and classic.",
    image_url:
      "https://images.unsplash.com/photo-1593702288056-fb7fbbd1ec74?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 60,
    price: 800,
    category: "package",
    is_visible: true,
    display_order: 8,
    created_at: "",
    updated_at: "",
  },
  {
    id: "color-package-plus",
    shop_id: null,
    name: "Haircut + Black Color + Shampoo + Face Mask/Gel",
    description: "Extended grooming package with face mask or gel.",
    image_url:
      "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 75,
    price: 1000,
    category: "package",
    is_visible: true,
    display_order: 9,
    created_at: "",
    updated_at: "",
  },
  {
    id: "vip",
    shop_id: null,
    name: "VIP Full Package",
    description: "Our signature VIP experience — every service combined for the ultimate grooming ritual.",
    image_url:
      "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 120,
    price: 3000,
    category: "vip",
    is_visible: true,
    display_order: 10,
    created_at: "",
    updated_at: "",
  },
];

export const SEED_BARBERS: Barber[] = [
  {
    id: "bernabas",
    shop_id: null,
    name: "Bernabas Mengistu",
    bio: "Skilled barber with expertise in modern cuts.",
    photo_url: "",
    experience_years: 0,
    branch_id: "piassa",
    working_days: ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],
    working_hours: { open: "08:00", close: "20:00" },
    is_active: true,
    is_featured: false,
    rating: 4.9,
    display_order: 1,
    created_at: "",
    updated_at: "",
  },
  {
    id: "tadesse",
    shop_id: null,
    name: "Tadesse Jember",
    bio: "Master of classic and contemporary styles.",
    photo_url: "",
    experience_years: 0,
    branch_id: "piassa",
    working_days: ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],
    working_hours: { open: "08:00", close: "20:00" },
    is_active: true,
    is_featured: false,
    rating: 4.8,
    display_order: 2,
    created_at: "",
    updated_at: "",
  },
  {
    id: "eyosiyas",
    shop_id: null,
    name: "Eyosiyas Anteneh",
    bio: "Precision cuts and beard craftsmanship.",
    photo_url: "",
    experience_years: 0,
    branch_id: "piassa",
    working_days: ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],
    working_hours: { open: "08:00", close: "20:00" },
    is_active: true,
    is_featured: false,
    rating: 4.85,
    display_order: 3,
    created_at: "",
    updated_at: "",
  },
  {
    id: "samuel",
    shop_id: null,
    name: "Samuel Derebew",
    bio: "Customer favorite with a passion for grooming.",
    photo_url: "",
    experience_years: 0,
    branch_id: "piassa",
    working_days: ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],
    working_hours: { open: "08:00", close: "20:00" },
    is_active: true,
    is_featured: false,
    rating: 4.9,
    display_order: 4,
    created_at: "",
    updated_at: "",
  },
  {
    id: "yalew",
    shop_id: null,
    name: "Yalew Tsega",
    bio: "Detail-oriented grooming specialist.",
    photo_url: "",
    experience_years: 0,
    branch_id: "piassa",
    working_days: ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],
    working_hours: { open: "08:00", close: "20:00" },
    is_active: true,
    is_featured: false,
    rating: 4.75,
    display_order: 5,
    created_at: "",
    updated_at: "",
  },
  {
    id: "getachew",
    shop_id: null,
    name: "Getachew Teka",
    bio: "Friendly barber with a sharp eye for style.",
    photo_url: "",
    experience_years: 0,
    branch_id: "piassa",
    working_days: ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],
    working_hours: { open: "08:00", close: "20:00" },
    is_active: true,
    is_featured: false,
    rating: 4.8,
    display_order: 6,
    created_at: "",
    updated_at: "",
  },
  {
    id: "ambachew",
    shop_id: null,
    name: "Ambachew Tesfaye",
    bio: "VIP specialist — exclusive premium grooming experiences at Bole.",
    photo_url: "",
    experience_years: 0,
    branch_id: "bole",
    working_days: ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],
    working_hours: { open: "08:00", close: "20:00" },
    is_active: true,
    is_featured: true,
    rating: 5.0,
    display_order: 7,
    created_at: "",
    updated_at: "",
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: "1",
    shop_id: null,
    customer_name: "Henok A.",
    rating: 5,
    content: "Best barber experience in Addis. Clean shop, skilled barbers, premium feel.",
    avatar_url: null,
    is_featured: true,
    created_at: "",
  },
  {
    id: "2",
    shop_id: null,
    customer_name: "Meron T.",
    rating: 5,
    content: "Booking was effortless and the haircut was flawless. Highly recommended.",
    avatar_url: null,
    is_featured: true,
    created_at: "",
  },
  {
    id: "3",
    shop_id: null,
    customer_name: "Yared K.",
    rating: 5,
    content: "The VIP package at Bole is worth every birr. Ambachew is a master.",
    avatar_url: null,
    is_featured: true,
    created_at: "",
  },
  {
    id: "4",
    shop_id: null,
    customer_name: "Bethel L.",
    rating: 5,
    content: "Professional team, modern atmosphere, consistent quality every visit.",
    avatar_url: null,
    is_featured: false,
    created_at: "",
  },
];

export const SEED_SOCIALS: SocialLink[] = [
  { id: "1", shop_id: null, platform: "instagram", url: "https://www.instagram.com/kemekem_barbershop", display_order: 1 },
  { id: "2", shop_id: null, platform: "tiktok", url: "https://www.tiktok.com/@kemekembarbershop", display_order: 2 },
  { id: "3", shop_id: null, platform: "facebook", url: "https://www.facebook.com/share/1LCfmr9Ckm/", display_order: 3 },
];

export const SEED_GALLERY: GalleryItem[] = [
  { id: "1", shop_id: null, image_url: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=900&q=80", category: "haircuts", title: "Classic cut", description: null, display_order: 1, created_at: "" },
  { id: "2", shop_id: null, image_url: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=900&q=80", category: "interior", title: "Piassa interior", description: null, display_order: 2, created_at: "" },
  { id: "3", shop_id: null, image_url: "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=900&q=80", category: "beard", title: "Beard work", description: null, display_order: 3, created_at: "" },
  { id: "4", shop_id: null, image_url: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=900&q=80", category: "before_after", title: "Transformation", description: null, display_order: 4, created_at: "" },
  { id: "5", shop_id: null, image_url: "https://images.unsplash.com/photo-1593702288056-fb7fbbd1ec74?auto=format&fit=crop&w=900&q=80", category: "haircuts", title: "Fade", description: null, display_order: 5, created_at: "" },
  { id: "6", shop_id: null, image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=900&q=80", category: "facial", title: "Facial treatment", description: null, display_order: 6, created_at: "" },
];