// Static seed data — used when Supabase is unavailable.
// Lets the site work without a database connection.

import type {
  Branch,
  Service,
  Barber,
  Review,
  BusinessSettings,
  SocialLink,
  GalleryItem,
} from "@/types/database";

export const SEED_SETTINGS: BusinessSettings = {
  shop_id: "default",
  business_name: "Kemekem Barbershop",
  tagline: "Look Sharp. Book in Seconds.",
  logo_url: null,
  favicon_url: null,
  hero_image_url:
    "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1920&q=80",
  hero_video_url: null,
  phone: "+251 924 657 777",
  email: "kemekemedia01@gmail.com",
  address: "Addis Ababa, Ethiopia",
  maps_url: null,
  business_hours: { open: "08:00", close: "20:00", days: "Mon-Sun" },
  primary_color: "#C89B3C",
  booking_interval_minutes: 30,
  seo_title: "Kemekem Barbershop — Premium Grooming in Addis Ababa",
  seo_description:
    "Professional grooming experience with skilled barbers, premium services, and easy online booking.",
  seo_keywords: null,
  og_image_url: null,
  footer_text: "Designed with ❤️ for modern grooming.",
  updated_at: new Date().toISOString(),
};

export const SEED_BRANCHES: Branch[] = [
  {
    id: "piassa",
    shop_id: null,
    name: "Piassa Branch",
    address: "Piassa Shopping Mall, 6th Floor",
    city: "Addis Ababa",
    phone: "+251 924 657 777",
    maps_url: "https://maps.google.com/?q=Piassa+Shopping+Mall+Addis+Ababa",
    working_hours: { open: "08:00", close: "20:00" },
    is_active: true,
    display_order: 1,
    created_at: "",
    updated_at: "",
  },
  {
    id: "bole",
    shop_id: null,
    name: "Bole Branch",
    address: "Sapphire Addis Hotel, 11th Floor, Bole",
    city: "Addis Ababa",
    phone: "+251 924 657 777",
    maps_url: "https://maps.google.com/?q=Sapphire+Addis+Hotel+Bole",
    working_hours: { open: "08:00", close: "20:00" },
    is_active: true,
    display_order: 2,
    created_at: "",
    updated_at: "",
  },
];

export const SEED_SERVICES: Service[] = [
  {
    id: "haircut",
    shop_id: null,
    name: "Haircut",
    description: "Precision cut tailored to your face shape and style.",
    image_url:
      "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 30,
    price: 250,
    category: "haircut",
    is_visible: true,
    display_order: 1,
    created_at: "",
    updated_at: "",
  },
  {
    id: "kids",
    shop_id: null,
    name: "Kids Haircut",
    description: "Gentle, patient grooming for children of all ages.",
    image_url:
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 20,
    price: 150,
    category: "haircut",
    is_visible: true,
    display_order: 2,
    created_at: "",
    updated_at: "",
  },
  {
    id: "beard",
    shop_id: null,
    name: "Beard Trim",
    description: "Sharp beard shaping, lining, and conditioning.",
    image_url:
      "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 15,
    price: 100,
    category: "beard",
    is_visible: true,
    display_order: 3,
    created_at: "",
    updated_at: "",
  },
  {
    id: "shaving",
    shop_id: null,
    name: "Shaving",
    description: "Classic hot towel straight-razor shave.",
    image_url:
      "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 30,
    price: 200,
    category: "shaving",
    is_visible: true,
    display_order: 4,
    created_at: "",
    updated_at: "",
  },
  {
    id: "wash",
    shop_id: null,
    name: "Hair Wash",
    description: "Refreshing wash, scalp massage, and towel dry.",
    image_url:
      "https://images.unsplash.com/photo-1559599076-9c61d8e1b77c?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 15,
    price: 80,
    category: "haircare",
    is_visible: true,
    display_order: 5,
    created_at: "",
    updated_at: "",
  },
  {
    id: "facial",
    shop_id: null,
    name: "Facial",
    description: "Deep cleansing facial treatment for men.",
    image_url:
      "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 45,
    price: 350,
    category: "skincare",
    is_visible: true,
    display_order: 6,
    created_at: "",
    updated_at: "",
  },
  {
    id: "color",
    shop_id: null,
    name: "Hair Coloring",
    description: "Premium coloring and grey blending.",
    image_url:
      "https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 60,
    price: 400,
    category: "haircare",
    is_visible: true,
    display_order: 7,
    created_at: "",
    updated_at: "",
  },
  {
    id: "vip",
    shop_id: null,
    name: "VIP Grooming",
    description: "Full luxury package: haircut, beard, facial, and massage.",
    image_url:
      "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=900&q=80",
    duration_minutes: 90,
    price: 800,
    category: "vip",
    is_visible: true,
    display_order: 8,
    created_at: "",
    updated_at: "",
  },
];

export const SEED_BARBERS: Barber[] = [
  {
    id: "abel",
    shop_id: null,
    name: "Abel Tesfaye",
    bio: "Master barber with 12 years of experience in modern and classic styles.",
    photo_url:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    experience_years: 12,
    branch_id: null,
    working_days: ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],
    working_hours: { open: "08:00", close: "20:00" },
    is_active: true,
    is_featured: true,
    rating: 4.95,
    display_order: 1,
    created_at: "",
    updated_at: "",
  },
  {
    id: "dawit",
    shop_id: null,
    name: "Dawit Mekonnen",
    bio: "Beard specialist and grooming expert.",
    photo_url:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    experience_years: 8,
    branch_id: null,
    working_days: ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],
    working_hours: { open: "09:00", close: "19:00" },
    is_active: true,
    is_featured: true,
    rating: 4.88,
    display_order: 2,
    created_at: "",
    updated_at: "",
  },
  {
    id: "yonas",
    shop_id: null,
    name: "Yonas Bekele",
    bio: "Creative stylist with a passion for fades and modern cuts.",
    photo_url:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80",
    experience_years: 6,
    branch_id: null,
    working_days: ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],
    working_hours: { open: "10:00", close: "20:00" },
    is_active: true,
    is_featured: false,
    rating: 4.80,
    display_order: 3,
    created_at: "",
    updated_at: "",
  },
  {
    id: "samuel",
    shop_id: null,
    name: "Samuel Girma",
    bio: "Senior barber known for precision and detail.",
    photo_url:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80",
    experience_years: 10,
    branch_id: null,
    working_days: ["monday","tuesday","wednesday","thursday","friday","saturday","sunday"],
    working_hours: { open: "08:00", close: "18:00" },
    is_active: true,
    is_featured: false,
    rating: 4.90,
    display_order: 4,
    created_at: "",
    updated_at: "",
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: "1",
    shop_id: null,
    customer_name: "Henok A.",
    rating: 5,
    content: "Best barber experience in Addis. Clean shop, skilled barbers, premium feel.",
    avatar_url: null,
    is_featured: true,
    created_at: "",
  },
  {
    id: "2",
    shop_id: null,
    customer_name: "Meron T.",
    rating: 5,
    content: "Booking was effortless and the haircut was flawless. Highly recommended.",
    avatar_url: null,
    is_featured: true,
    created_at: "",
  },
  {
    id: "3",
    shop_id: null,
    customer_name: "Yared K.",
    rating: 5,
    content: "Love the Bole branch. The VIP grooming package is worth every birr.",
    avatar_url: null,
    is_featured: true,
    created_at: "",
  },
  {
    id: "4",
    shop_id: null,
    customer_name: "Bethel L.",
    rating: 5,
    content: "Professional team, modern atmosphere, and consistent quality every visit.",
    avatar_url: null,
    is_featured: false,
    created_at: "",
  },
];

export const SEED_SOCIALS: SocialLink[] = [
  { id: "1", shop_id: null, platform: "instagram", url: "https://instagram.com/kemekem", display_order: 1 },
  { id: "2", shop_id: null, platform: "telegram", url: "https://t.me/kemekem", display_order: 2 },
  { id: "3", shop_id: null, platform: "tiktok", url: "https://tiktok.com/@kemekem", display_order: 3 },
  { id: "4", shop_id: null, platform: "facebook", url: "https://facebook.com/kemekem", display_order: 4 },
];

export const SEED_GALLERY: GalleryItem[] = [
  { id: "1", shop_id: null, image_url: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=900&q=80", category: "haircuts", title: "Classic cut", description: null, display_order: 1, created_at: "" },
  { id: "2", shop_id: null, image_url: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=900&q=80", category: "interior", title: "Piassa interior", description: null, display_order: 2, created_at: "" },
  { id: "3", shop_id: null, image_url: "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=900&q=80", category: "beard", title: "Beard work", description: null, display_order: 3, created_at: "" },
  { id: "4", shop_id: null, image_url: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=900&q=80", category: "before_after", title: "Transformation", description: null, display_order: 4, created_at: "" },
  { id: "5", shop_id: null, image_url: "https://images.unsplash.com/photo-1593702288056-fb7fbbd1ec74?auto=format&fit=crop&w=900&q=80", category: "haircuts", title: "Fade", description: null, display_order: 5, created_at: "" },
  { id: "6", shop_id: null, image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=900&q=80", category: "facial", title: "Facial treatment", description: null, display_order: 6, created_at: "" },
];